# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GRM-Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GRM-Swift

  target 'GRM-SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end
 
  pod 'RealmSwift', '~> 3.7'
  pod 'Alamofire', '~> 4.7'
  pod 'RxSwift', '~> 4.2'
  pod 'RxSwiftExt/Core', '~> 3.3'
  
end
